/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
  // const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//export default {
//  myAutogeneratedSidebar: [
//    {
 //     type: 'autogenerated',
 //     dirName: '.', // '.' means the current docs folder
 //   },
//  ],
//};
 
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Wiki',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
//};

//export default sidebars;

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation 

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').Sidebarsconfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  Sidebar: [
    '1listo/Home',
    '1listo/Install',
    '1listo/GameBalance',
    '1listo/SpellsFeatsClassesItems',
    '1listo/ChangeLog',
  ],
};

export default sidebars;
