#!/usr/bin/env python3
"""Audit raw text and duplicate stat identities; never modify mod files."""
from pathlib import Path
from collections import Counter, defaultdict
import csv
import hashlib
import re
import unicodedata
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'ListoPatches/Public/ListoPatches/Stats/Generated/Data'
OUT = ROOT / 'reports/listopatches-audit'
OUT.mkdir(parents=True, exist_ok=True)

def special(text):
    return [(i + 1, f'U+{ord(c):04X}') for i, c in enumerate(text)
            if (unicodedata.category(c).startswith('C') and c not in '\r\n\t')
            or c == '\ufffd']

def canonical(lines):
    return '\n'.join(l.strip() for l in lines
                     if l.strip() and not l.lstrip().startswith('//'))

groups = defaultdict(list)
issues = []
files = sorted(DATA.rglob('*.txt'))
for path in files:
    text = path.read_bytes().decode('utf-8-sig', errors='strict')
    assert not special(text), (path, special(text))
    lines = text.splitlines()
    starts = [i for i, l in enumerate(lines)
              if re.match(r'^\s*new\s+entry\s+"', l)]
    for j, start in enumerate(starts):
        end = starts[j + 1] if j + 1 < len(starts) else len(lines)
        block = lines[start:end]
        name = re.match(r'^\s*new\s+entry\s+"([^"]+)"', block[0])[1]
        types = [m[1] for l in block
                 if (m := re.match(r'^\s*type\s+"([^"]+)"', l))]
        assert len(types) == 1, (path, start + 1, name, types)
        groups[types[0], name].append({
            'file': path.relative_to(DATA).as_posix(), 'line': start + 1,
            'body': canonical(block),
            'fields': dict((m[1], m[2]) for l in block
                           if (m := re.match(r'^\s*data\s+"([^"]+)"\s*"(.*)"\s*$', l))),
        })
    if path.name == 'SPELLS.txt':
        for i, line in enumerate(lines, 1):
            s = line.strip()
            if s and not s.startswith('//') and not re.fullmatch(
                    r'(new entry|type|using) "[^"]*"|data "[^"]*" ".*"', s):
                issues.append((i, s))

duplicates = {k: v for k, v in groups.items() if len(v) > 1}
identical = sum(len({o['body'] for o in v}) == 1 for v in duplicates.values())
report = ['# ListoPatches duplicate entry review', '',
          'Scope: `ListoPatches/Public/ListoPatches/Stats/Generated/Data/**/*.txt`.', '',
          'Identity is the exact, case-sensitive `(type, name)` pair. Different types sharing a name are not duplicates. All occurrences are retained for review.', '',
          f'- Files scanned: {len(files)}',
          f'- Declarations: {sum(map(len, groups.values()))}',
          f'- Unique identities: {len(groups)}',
          f'- Repeated identities: {len(duplicates)}',
          f'- Occurrences in repeated identities: {sum(map(len, duplicates.values()))}',
          f'- Occurrences beyond one per identity: {sum(len(v)-1 for v in duplicates.values())}',
          f'- Groups with identical declaration lines: {identical}',
          f'- Groups with differing declaration lines: {len(duplicates)-identical}', '',
          'Comparison ignores blank lines, comment-only lines, and outer line whitespace; it preserves directive order and quoted values. Differing groups may also contain identical subsets.', '',
          'Locations below are relative to the Data folder, with 1-based line numbers in this PR.', '']
rows = []
for (kind, name), occurrences in sorted(duplicates.items()):
    bodies = {o['body'] for o in occurrences}
    classification = 'identical declarations' if len(bodies) == 1 else 'differing declarations'
    report += [f'## {kind}: `{name}`', '', f'{len(occurrences)} occurrences; {classification}.', '']
    fields = sorted(set().union(*(o['fields'] for o in occurrences)))
    differences = [f for f in fields if len({o['fields'].get(f) for o in occurrences}) > 1]
    if differences:
        report += ['Differing data fields: ' + ', '.join(f'`{f}`' for f in differences) + '.', '']
    for o in occurrences:
        rel = 'ListoPatches/Public/ListoPatches/Stats/Generated/Data/' + o['file']
        link = '../../' + rel.replace(' ', '%20') + f"#L{o['line']}"
        report.append(f"- [{o['file']}:{o['line']}]({link})")
        rows.append([kind, name, classification, o['file'], o['line'],
                     hashlib.sha256(o['body'].encode()).hexdigest()])
    report.append('')
(OUT / 'duplicates.md').write_text('\n'.join(report), encoding='utf-8')
with (OUT / 'duplicate-occurrences.csv').open('w', newline='', encoding='utf-8') as f:
    w = csv.writer(f)
    w.writerow(['type', 'name', 'classification', 'file', 'line', 'declaration_sha256'])
    w.writerows(rows)

report = ['# Raw text validation', '', 'Generated by `python tools/audit_listopatches.py`.', '']
xml_bytes = []
for path in sorted((ROOT / 'ListoPatches/Localization/English').glob('*.xml')):
    raw = path.read_bytes()
    text = raw.decode('utf-8', errors='strict')
    root = ET.fromstring(raw)
    assert root.tag == 'contentList'
    assert all(e.tag == 'content' and not len(e) and 'contentuid' in e.attrib for e in root)
    assert not special(text)
    counts = Counter(e.get('contentuid') for e in root)
    assert all(n == 1 for n in counts.values())
    assert '<!DOCTYPE' not in text and '<?xml-stylesheet' not in text
    assert '&amp;lt;' not in text and '&amp;gt;' not in text
    xml_bytes.append(raw)
    report += [f'## {path.name}', '',
               f'- Bytes: {len(raw)}; lines: {len(text.splitlines())}; content entries: {len(root)}.',
               '- Strict UTF-8 decoding and XML parsing: pass.',
               '- Hidden controls, replacement characters, duplicate contentuids, nested XML inside content elements: 0.',
               '- No DTD, external entity declarations, stylesheet instructions, or double-escaped angle brackets.',
               '- Non-ASCII characters: ' + ', '.join(f'U+{ord(c):04X} {unicodedata.name(c)} ({n})' for c, n in sorted(Counter(c for c in text if ord(c)>127).items())) + '.',
               f'- SHA-256: `{hashlib.sha256(raw).hexdigest()}`.', '']
assert len(xml_bytes) == 2 and xml_bytes[0] == xml_bytes[1]
spell = DATA / 'SPELLS.txt'
raw = spell.read_bytes()
text = raw.decode('utf-8')
assert text.isascii() and not special(text)
report += ['## SPELLS.txt after restoration', '',
           f'- Bytes: {len(raw)}; lines: {len(text.splitlines())}.',
           '- Strict UTF-8: pass; all characters are ASCII.',
           '- Hidden controls, replacement characters, embedded BOMs, and non-ASCII characters: 0.',
           f'- SHA-256: `{hashlib.sha256(raw).hexdigest()}`.', '',
           'The following seven source-inherited lines lack whitespace between the data key and quoted value. They are flagged, not changed; this audit does not establish how the game parser handles that syntax.', '']
report += [f'- Line {i}: `{s}`' for i, s in issues]
report += ['', '## Scope limitations', '',
           'XML validity does not validate BG3 handles, tooltip semantics, or in-game resolution. Stat checks cover encoding, entry structure, and duplicates, not the full game grammar or gameplay behavior.', '']
(OUT / 'validation.md').write_text('\n'.join(report), encoding='utf-8')
print(f'{len(files)} files; {len(duplicates)} duplicate groups; {len(rows)} duplicate occurrences; XML and UTF-8 checks passed')
